# Generated by Django 4.2.6 on 2025-02-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='series',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
