# Generated by Django 4.2.6 on 2025-02-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_season_cover_series_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['created'], 'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
    ]
