# Generated by Django 4.2.12 on 2025-03-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_season_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
