# Generated by Django 4.2.12 on 2025-03-20 15:12

import cinema.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_series_name_alter_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='counter',
            field=cinema.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
