# Generated by Django 4.2.12 on 2025-03-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_season_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='title',
        ),
    ]
