# Generated by Django 4.2.12 on 2025-03-21 10:27

import cinema.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_season_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='counter',
            field=cinema.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
