# Generated by Django 4.2.12 on 2025-04-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_alter_comment_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='season',
            name='description',
        ),
    ]
