# Generated by Django 4.2.12 on 2025-05-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_rating_created_rating_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
