# Generated by Django 4.2.12 on 2025-05-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_rating_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
